[package]
name = "safe-vex"
version = "3.1.10"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "A modular, reliable and comprehensive wrapper around the vex-rt library that never crashes."
authors = ["kalscium <kalscium@protonmail.com>"]
repository = "https://github.com/kalscium/safe-vex"
keywords = [ "robot", "robotics", "vex", "vex-rt", "wrapper" ]
categories = [ "no-std", "external-ffi-bindings", "hardware-support", "api-bindings" ]
readme = "README.md"

[lib]
name = "safe_vex"
path = "src/lib.rs"

[dependencies]
vex-rt = "0.15.1"
